-- =====================================================================================
-- V4 — Signed checkpoints of the journal (LOCAL Signed Tree Head pattern).
--
-- Every checkpoint SIGNS the head of the hash-chain (entry_hash of the posting_hash with the highest seq),
-- which is the accumulated cryptographic commitment of the WHOLE journal. The signature is ML-DSA-65
-- (FIPS 204, post-quantum): it anchors the head IN TIME under a commitment resistant to a
-- future quantum forger ("forge-later").
--
-- HONEST SCOPE (what this is NOT): it is a *local* STH, not Certificate Transparency. It lacks what
-- gives CT its strong guarantee: publishing the head to external monitors/auditors (gossip) and
-- anchoring the public key OUTSIDE this DB (RFC 3161 TSA, transparency log, WORM in another account).
-- Without that, an actor with write access to the DB can rewrite posting + posting_hash + this row
-- consistently. The public key is stored here for auditability, NOT as a root of trust.
-- updatable=false on the entity is a JPA intent; real immutability requires REVOKE/WORM in prod.
-- =====================================================================================
CREATE TABLE journal_checkpoint (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_seq   BIGINT         NOT NULL UNIQUE,          -- seq of the signed head (1 checkpoint per head)
    head_hash   VARCHAR(64)    NOT NULL,                 -- entry_hash of the head (what is signed)
    algorithm   VARCHAR(32)    NOT NULL,                 -- p.ej. ML-DSA-65 (crypto-agility)
    public_key  VARCHAR(10000) NOT NULL,                 -- X.509 public key (base64) that signed
    signature   VARCHAR(10000) NOT NULL,                 -- signature (base64) over the canonical message
    signed_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);
-- chain_seq UNIQUE already creates its btree index; no extra index is needed.
