-- =====================================================================================
-- V4 — Checkpoints firmados del journal (patron Signed Tree Head LOCAL).
--
-- Cada checkpoint FIRMA la cabeza de la hash-chain (entry_hash del posting_hash con mayor seq),
-- que es el commitment criptografico acumulado de TODO el journal. La firma es ML-DSA-65
-- (FIPS 204, post-cuantica): ancla la cabeza EN EL TIEMPO bajo un compromiso resistente a un
-- futuro falsificador cuantico ("forge-later").
--
-- ALCANCE HONESTO (lo que esto NO es): es un STH *local*, no Certificate Transparency. Le falta lo
-- que da la garantia fuerte de CT: publicar la cabeza a monitores/auditores externos (gossip) y
-- anclar la clave publica FUERA de esta DB (TSA RFC 3161, log de transparencia, WORM en otra cuenta).
-- Sin eso, un actor con escritura en la DB puede reescribir posting + posting_hash + esta fila de
-- forma consistente. La clave publica se guarda aca por auditabilidad, NO como raiz de confianza.
-- updatable=false en la entidad es intencion JPA; la inmutabilidad real exige REVOKE/WORM en prod.
-- =====================================================================================
CREATE TABLE journal_checkpoint (
    id          BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_seq   BIGINT         NOT NULL UNIQUE,          -- seq de la cabeza firmada (1 checkpoint por cabeza)
    head_hash   VARCHAR(64)    NOT NULL,                 -- entry_hash de la cabeza (lo que se firma)
    algorithm   VARCHAR(32)    NOT NULL,                 -- p.ej. ML-DSA-65 (crypto-agility)
    public_key  VARCHAR(10000) NOT NULL,                 -- clave publica X.509 (base64) que firmo
    signature   VARCHAR(10000) NOT NULL,                 -- firma (base64) sobre el mensaje canonico
    signed_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);
-- chain_seq UNIQUE ya crea su indice btree; no hace falta un indice extra.
